name: Build Android Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Set up Android SDK
      uses: reactivecircuits/setup-android@v2
      with:
        components: 'build-tools;29.0.3,platform-tools,tools'
        licenses: ${{ secrets.ANDROID_SDK_LICENSE }}

    - name: Set up Android NDK
      uses: r0mka/android-action@v2
      with:
        components: 'cmake;3.18.1,ndk;21.1.6273396'

    - name: Build Android Project
      run: |
        ./gradlew aR
